# Generated by Django 5.0.2 on 2024-05-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceTracker', '0002_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('dining', 'Dining Out'), ('transportation', 'Transportation'), ('clothing', 'Clothing'), ('grocery', 'Grocery'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities')], max_length=50),
        ),
    ]
